require "./lib/gameoflife_rules"
require "./lib/game"

describe "Acceptance test for minesweeper" do
  
  it "Should take two complex field as input and reveal them" do
    game = Game.new <<-INPUT
4 4
*...
....
.*..
....
3 5
**...
.....
.*...
0 0    
INPUT

    game.reveal_fields.should == <<-OUTPUT
Field #1:
*100
2210
1*10
1110

Field #2:
**100
33200
1*100
OUTPUT
  end
  
end


describe "Acceptance test for gameoflife" do
  
  it "a blank field will remain blank" do
    input = <<-INPUT
4 4
....
....
....
....
0 0    
INPUT
    game = Game.new(input, GameoflifeRules.new)
    game.next_iteration!
    game.reveal_fields.should == <<-OUTPUT
Field #1:
....
....
....
....
OUTPUT
  end
  
  it "a dying field will become blank" do
    input = <<-INPUT
4 4
#...
..#.
....
#..#
0 0    
INPUT
    game = Game.new(input, GameoflifeRules.new)
    game.next_iteration!
    game.reveal_fields.should == <<-OUTPUT
Field #1:
....
....
....
....
OUTPUT
  end    
  
  it "a living field will live" do
    input = <<-INPUT
9 21
.....................
.....................
.....................
........#............
..........#..........
.......##..###.......
.....................
.....................
.....................
0 0    
INPUT
    output = <<-OUTPUT
Field #1:
.....................
.....................
.....................
...........##........
...........##.....#..
.................#.#.
......##.........#.#.
.....#..#.........#..
......##.............
OUTPUT
    game = Game.new(input, GameoflifeRules.new)
    game.next_iteration!(90)
    game.reveal_fields.should == output
  end

end